### ISSUE TITLE
quite fd on macOS unfortunately

### ISSUE THREAD

**Issue by castdrian** [DaBluLite/MobileV2#1]
https://github.com/DaBluLite/MobileV2/assets/22133246/6a00dd4f-6bf3-4c43-aefd-1ce859b15c41

**Comment by DaBluLite** [comment]
```css
.withFrame-2dL45i,
.titleBar-1it3bQ {
  background: none !important;
}
```
Could you try this?

**Comment by castdrian** [comment]
unfortunately didn't resolve anything in regards to the fav tab and the menubar styling
<img width="236" alt="ishare-1691493790" src="https://github.com/DaBluLite/MobileV2/assets/22133246/aa456d37-d1b0-4433-b025-22471654cadb">

**Comment by DaBluLite** [comment]
```css
.platform-osx .wrapper-1_HaEi {
  margin-top: 0 !important;
  padding-top: 32px;
}
```
try this
